#pragma config(Motor,  port1,           rightDrive,    tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           armServo,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           trackDriveY,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          leftDrive,     tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true){
			motor[leftDrive] = vexRT[Ch3];
			motor[rightDrive] = vexRT[Ch2];

			//while(vexRT[Btn8R]){
			//	motor[armServo] = - vexRT[Ch2];
			//	motor[trackDriveY] = vexRT[Ch3];
			//}
	}
}
