#pragma config(Sensor, in1,    ArmPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  Sonar,          sensorSONAR_mm)
#pragma config(Sensor, dgtl3,  LQuad,          sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  RQuad,          sensorQuadEncoder)
#pragma config(Motor,  port1,           LDrive1,       tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           LDrive2,       tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port3,           Aim,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           Reload,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           ServoFire,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           RDrive2,       tmotorServoContinuousRotation, openLoop, driveRight)
#pragma config(Motor,  port10,          RDrive1,       tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

	int rDrive = 0;
	int lDrive = 0;

//Program Sketch
task main()
{

	//Constant Loop
	while(1 == 1)
	{
		//Tank Drive Input
		rDrive = vexRT[Ch3];
		lDrive = vexRT[Ch2];

		if (vexRT[Btn6U]){
			rDrive = 127;
			lDrive = -127;
		}
		if (vexRT[Btn5U]){
			rDrive = -127;
			lDrive = 127;
		}
		if (vexRT[Btn7U]){
			motor[Aim] = 50;
		} else if (vexRT[Btn7D]){
			motor[Aim] = -50;
		} else {
			motor[Aim] = 0;
		}

		if (vexRT[Btn8R]){
			motor[ServoFire] = -55;
			delay(1000);
			motor[ServoFire] = 42;
			delay(1000);
			motor[ServoFire] = 0;
		}
		if (vexRT[Btn8L]){
			motor[Aim] = -10;
			motor[Reload] = 50;
			delay(5000);
			motor[Aim] = 0;
			motor[Reload] = -20;
			delay(3500);
			motor[Reload] = 0;
		} else {
			motor[Reload] = 0;
		}





		//Drive
		motor[LDrive1]  = lDrive;   // Left Joystick Y value
		motor[LDrive2]  = lDrive;   // Left Joystick Y value
		motor[RDrive1] = rDrive;   // Right Joystick Y value
		motor[RDrive2] = rDrive;   // Right Joystick Y value
	}
}
