#pragma config(Sensor, in1,    IR,             sensorLineFollower)
#pragma config(Sensor, in2,    marbleSens,     sensorLineFollower)
#pragma config(Sensor, dgtl1,  redLED,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  orangeLED,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  clearLED,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  blueLED,        sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, endStop,        sensorTouch)
#pragma config(Motor,  port1,           Spin,          tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port8,           Buckets,       tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           Servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Code Variables
int isBlue = 0;
int isClear = 1;
int isOrange = 2;
int isRed = 3;

int marbleSensCal = 3050;
int marbleSensTol = 50;

//Marble Calibration Values
int blueMarble = 1600; //1590
int clearMarble = 1560; //1560
int orangeMarble = 1700; //1700
int redMarble = 1560; //1560
//OLD
//int blueMarble = 1560; //1590
//int clearMarble = 1530; //1560
//int orangeMarble = 1540; //1700
//int redMarble = 1550; //1560

int marbleTol = 4;

//Bucket Position
int blueBucket = -120;
int clearBucket = -40;
int orangeBucket = 30;
int redBucket = 110;


int lastIR = 0;


//Helper Methods

//Moves to marble bucket
void toBucket(int Marble){
	if (Marble == isBlue){
		motor[Buckets] = blueBucket;
	}
	if (Marble == isClear){
		motor[Buckets] = clearBucket;
	}
	if (Marble == isOrange){
		motor[Buckets] = orangeBucket;
	}
	if (Marble == isRed){
		motor[Buckets] = redBucket;
	}
}

//Sets Marble Indicator
int setLED(int LED){
	SensorValue[redLED] = (isRed == LED ? 1 : 0);
	SensorValue[orangeLED] = (isOrange == LED ? 1 : 0);
	SensorValue[clearLED] = (isClear == LED ? 1 : 0);
	SensorValue[blueLED] = (isBlue == LED ? 1 : 0);
	return LED;
}

//Returns Current Marble (-1 if none)
int readMarble(){
	//Value
	int IRV = SensorValue[IR];
	//Blue Marble
	if (abs(blueMarble - IRV) < marbleTol){
		return isBlue;
	}
	//Red Marble
	if (abs(redLED - IRV) < marbleTol){
		return isRed;
	}
	//Orange Marble
	if (abs(orangeMarble - IRV) < marbleTol){
		return isOrange;
	}
	//Clear Marble
	if (abs(clearMarble - IRV) < marbleTol){
		return isClear;
	}
	//Unknown
	return -1;
}

//Feeds 1 marble, returns what was fed
int feedWeedNRead(){
	//Open Sprocket
	motor[Servo] = -10;
	//Wait
	delay(200);
	int mar = -1;
	while (mar == -1){
		motor[Servo] = -20;
		delay(200);
		motor[Servo] = 40;
		lastIR = SensorValue[IR];
		mar = readMarble();
		delay(500);
	}

	motor[Servo] = 127;
	delay(200);
	motor[Servo] = -10;
		return mar;
}

task main()
{
	while (true){
		toBucket(setLED(feedWeedNRead()));
		delay(100);
	}
}
